# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 11:26
from __future__ import unicode_literals

from django.db import migrations



def update_package_name(apps, schema_editor):
    AbstractWidget = apps.get_model("workflows", "AbstractWidget")

    for aw in AbstractWidget.objects.all():
        aw.name = "%s %s" % (aw.name, aw.package)

        new_package_names={'nltoolkit':'tf_core.nltoolkit',
                           'latino':'tf_latino.latino',
                           'lemmagen':'tf_latino.lemmagen',
                           'literature_based_discovery':'tf_literature_based_discovery'}
        if aw.package in new_package_names:
            aw.package=new_package_names[aw.package]
            aw.save()

def clear_widgets_with_adc(apps, schema_editor):
    Widget = apps.get_model("workflows", "Widget")

    Widget.objects.filter(inputs__short_name="adc").update(finished=False)
    Widget.objects.filter(outputs__short_name="adc").update(finished=False)
    Widget.objects.filter(workflow_link__isnull=False, workflow_link__widgets__inputs__short_name='adc')\
        .update(finished=False)
    Widget.objects.filter(workflow_link__isnull=False, workflow_link__widgets__outputs__short_name='adc')\
        .update(finished=False)

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
                migrations.RunPython(update_package_name),
                migrations.RunPython(clear_widgets_with_adc)
    ]
