# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20161027_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ('order', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ('order', 'pk')},
        ),
        migrations.AlterField(
            model_name='abstractwidget',
            name='windows_queue',
            field=models.BooleanField(default=False, help_text=b'Widget is required to be run on a Windows platform.'),
        ),
    ]
